### PR TITLE
Separate tests in small files

### LINKED ISSUE #244: Split tests in several files and remove them from the package distribution
Hi @carljm ,

I think it would be better to split the tests in several files.

It would:
- Improve test readability,
- Reduce merge conflicts between PRs.

I also think that's not really useful to distribute the tests with the python package, they could live outside of the `model_utils` folder.

What do you think?

### PR DESCRIPTION
**Pull request by romgar**
It makes it easier to edit / add new ones / reduce conflicts on different merge requests.
Aim to fix #244.

### CODE REVIEW

**Comment by carljm** [comment]
Assuming Travis run passes, and overall test count is the same as before (check output of previous Travis runs), I'm fine with you going ahead and merging this.

**Comment by romgar** [comment]
More tests run on Django `1.6`. I will have a look and fix it.

**Comment by romgar** [comment]
Ok, I found 2 issues:
- Manually importing all tests (in `__init__` files) to make it work for Django 1.4/1.5 duplicates all test run for Django 1.6 (!) and is harmless for Django 1.7+,
- Inheritance in some TestCases were duplicating some tests if placed in different files (related to test runner introspection?).

It seems to be fine now, I will go through all the travis builds to confirm it.

**Comment by romgar** [comment]
I went through all builds, it's alright!

**Pull request merged**
