### PR TITLE
Dependencies version bump

### LINKED ISSUE #152: Update .travis.yml and tox.ini to run on Django 1.7

### LINKED ISSUE #153: Update .travis.yml and tox.ini to run on Python 3.4

### PR DESCRIPTION
**Pull request by orgkhnargh**
Going to do a little work on bumping dependencies versions in tox.ini and .travis.yml up to latest.

Here is list of changes I am going to implement in this PR:
* bump django  from 1.4.10 to 1.4.18
* bump django  from 1.5.5 to 1.5.12
* bump django  from 1.6.1 to 1.6.10
* add django 1.7.3 to test environments (fix #152)
* add django 1.8a1 to test environments (it is on pypi already, why not test it?)
* do not include south on django trunk (master) environments (south is not required since 1.7)
* add python3.4 environments for django 1.7, 1.8 and trunk  (fix #153)

### CODE REVIEW

**Comment by carljm** [comment]
Awesome, thanks!

While you're working on the tox setup, you could consider also updating to the latest `tox.ini` syntax using generative environments / factors: http://tox.readthedocs.org/en/latest/config.html#generating-environments-conditional-settings -- I think that could reduce the size of `tox.ini` quite a lot and make it easier to maintain.

We could also consider trying to use tox on Travis to avoid maintaining separate configs. I don't feel strongly either way about that.

**Comment by orgkhnargh** [comment]
I'll update `tox.ini` syntax. But I am not sure if I can handle using tox on Travis. I will think about it later.

**Comment by carljm** [comment]
Sure, whatever you're interested in doing is great. I'm not entirely sure about how to switch to tox on Travis while maintaining parallel builds on Travis anyway.

**Comment by orgkhnargh** [comment]
OK, I know now how to deal with tox on Travis. The main idea is to explicitly tell tox it's environment name and run tox for each environment separately. Take a look at this [`.travis.yml`](https://github.com/eventlet/eventlet/blob/master/.travis.yml#L3-L19). I will do that today, if you don't mind.

**Comment by orgkhnargh** [comment]
And also I will mark builds of django 1.8 and trunk allowed to fail as made in example above.

**Comment by treyhunner** [comment]
Personally, that `.travis.yml` file doesn't look easier to maintain to me than manually maintaining separate versions.

Could `tox --listenvs` be used to shorten it somehow?

**Comment by orgkhnargh** [comment]
I wrote shell script to update envs in `.travis.yml`. [link](https://github.com/orgkhnargh/django-model-utils/blob/dependencies_version_bump/update_travis_envs.sh)

I did not find `tox --listenvs` before. I will now adapt that shell script to use this command instead of `tox --showconfig`.

**Comment by orgkhnargh** [comment]
Previously you had to maintain both `.travis.yml` and `tox.ini`. Now you only need to update `tox.ini` and run script which will adapt envs in `.travis.yml` according to changes in `tox.ini`.

**Comment by orgkhnargh** [comment]
All planned tasks on this PR is done.

Can anybody review this, please?

**Comment by carljm** [comment]
This looks great to me! Thanks for your work. Merging.

Now I just need to find time to get the tests passing on 1.8/master...

**Pull request merged**
