### PR TITLE
Fix #214

### LINKED ISSUE #214: FieldTracker doesn't work properly for ForeignKeys in inherited models
Example:
```python
class A(Model):
    blah = fields.ForeignKey(OtherModel)
    tracker = FieldTracker('blah')

class B(A):
    pass

b = B.objects.get()
b.tracker.field_map['blah'] == 'blah' # But it should be blah_id
```

I believe this is due to the use of `local_fields`

### PR DESCRIPTION
**Pull request by mikebryant**

### CODE REVIEW

**Comment by mikebryant** [comment]
@carljm What do I need to do to get this merged & released?

**Comment by carljm** [comment]
@mikebryant Sorry, this came while I was on vacation and had GitHub notifications turned off. Looks good to me; merging.

**Comment by carljm** [comment]
Released in 2.5.

**Comment by mikebryant** [comment]
Awesome, thank you!

**Pull request merged**
