### PR TITLE
Ability to purge from db a SoftDeletableModel

### PR DESCRIPTION
**Pull request by browniebroke**
This is useful when testing and in some edge cases.

### CODE REVIEW

**Comment by carljm** [comment]
Shouldn't need to copy the method; can use `super()` to call the parent `delete()` method.

**Comment by browniebroke** [comment]
Sorry, wasn't thinking straight, I will update soon.

**Comment by browniebroke** [comment]
Updated to call the parent `delete()` and squashed commits.

**Comment by charettes** [comment]
What about adding a `soft=True` kwarg to `delete()` instead?

**Comment by carljm** [comment]
Yeah, I'd be fine with an added kwarg to `delete`, tbh.

**Comment by carljm** [comment]
LGTM, merging. Thanks for making the updates!

**Pull request merged**
