### PR TITLE
Support for Django 1.10

### LINKED ISSUE #184: get_all_related_objects deprecation warning with Django 1.8
https://github.com/carljm/django-model-utils/blob/master/model_utils/managers.py#L103 raises the following deprecation warning in Django 1.8: 

```django.utils.deprecation.RemovedInDjango110Warning: 'get_all_related_objects is an unofficial API that has been deprecated. You may be able to replace it with 'get_fields()'```

### PR DESCRIPTION
**Pull request by bogdal**
This PR adds compatibility with Django `1.10`.
Fixes #184

### CODE REVIEW

**Comment by carljm** [comment]
Whoops, hold on, sorry, let's not duplicate work. I'm working on updating tox.ini and .travis.yml to remove unsupported versions as well in #208. Once I've got that done I'll merge it to master and you can rebase this on master, and then you should be good. Let's keep the tox/travis changes separate from the code changes.

Thanks for the PR!

**Comment by bogdal** [comment]
Awesome :+1: I'm waiting.

**Comment by carljm** [comment]
@bogdal Ok, tox/travis updates merged to master and pushed; you're all set! Maybe you can remove your second commit, rebase the first one, and force-push that, and we'll see what Travis has to say?

**Comment by bogdal** [comment]
Sure thing. :zap:  But I still see `py33-django_trunk` tox/travis env. I bet we'll see red :red_circle:

**Comment by carljm** [comment]
Ok, good point :-) Sorry, I cought 1.9 but not trunk. And I didn't notice the red because I have Django trunk failures configured to not break the overall build, and the trunk builds were all red anyway.

Pushed a commit on master to remove py33/trunk; if that's the only one that fails on the build here, I'll consider it good to go. Thanks again!

**Pull request merged**
